language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install coverage
  - pip install coveralls

script: nosetests

after_success:
  - coverage combine
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: always
